FROM golang:1.13.5

RUN mkdir -p /go/src/github.com/huajiao-tv/peppercron

WORKDIR /go/src/github.com/huajiao-tv/peppercron

COPY ./ /go/src/github.com/huajiao-tv/peppercron

RUN go build

FROM alpine:latest

RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2

RUN mkdir -p /data/peppercron && mkdir -p /data/peppercron/log

WORKDIR /data/peppercron

COPY --from=0 /go/src/github.com/huajiao-tv/peppercron/peppercron .

ENTRYPOINT ["./peppercron"]
